// Generato da `npm run db:schema` (scripts/schema-sql.ts): non modificare a mano.
// Lo esegue `initSchema()` in lib/db/index.ts solo su un DB senza tabelle.
export const SCHEMA_SQL: string[] = [
  "CREATE TABLE `areas` (\n\t`slug` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`tagline` text DEFAULT '' NOT NULL,\n\t`symbol` text DEFAULT '·' NOT NULL,\n\t`module` text,\n\t`position` integer DEFAULT 0 NOT NULL,\n\t`created_at` integer\n);\n",
  "CREATE TABLE `cards` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`domain_id` integer,\n\t`question` text NOT NULL,\n\t`answer` text NOT NULL,\n\t`source_chunk_id` integer,\n\t`ease` real DEFAULT 2.5 NOT NULL,\n\t`interval_days` integer DEFAULT 0 NOT NULL,\n\t`repetitions` integer DEFAULT 0 NOT NULL,\n\t`due_at` integer,\n\t`created_at` integer,\n\tFOREIGN KEY (`domain_id`) REFERENCES `domains`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`source_chunk_id`) REFERENCES `chunks`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
  "CREATE TABLE `chunks` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`document_id` integer NOT NULL,\n\t`ordinal` integer NOT NULL,\n\t`content` text NOT NULL,\n\t`meta` text,\n\tFOREIGN KEY (`document_id`) REFERENCES `documents`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
  "CREATE TABLE `concept_maps` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`domain_id` integer,\n\t`title` text NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL,\n\t`doc` text NOT NULL,\n\t`updated_at` integer,\n\tFOREIGN KEY (`domain_id`) REFERENCES `domains`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
  "CREATE TABLE `documents` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`domain_id` integer,\n\t`title` text NOT NULL,\n\t`source` text,\n\t`kind` text DEFAULT 'text' NOT NULL,\n\t`meta` text,\n\t`created_at` integer,\n\tFOREIGN KEY (`domain_id`) REFERENCES `domains`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
  "CREATE TABLE `domains` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text,\n\t`parent_id` integer,\n\t`kind` text DEFAULT 'course' NOT NULL,\n\t`path` text,\n\t`areas` text DEFAULT '[]' NOT NULL,\n\t`created_at` integer\n);\n",
  "CREATE TABLE `ingested_files` (\n\t`domain_id` integer NOT NULL,\n\t`source` text NOT NULL,\n\t`file_hash` text NOT NULL,\n\tPRIMARY KEY(`domain_id`, `source`),\n\tFOREIGN KEY (`domain_id`) REFERENCES `domains`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
  "CREATE TABLE `notes` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`content` text NOT NULL,\n\t`domain` text,\n\t`course_id` integer,\n\t`created_at` integer NOT NULL\n);\n",
  "CREATE TABLE `sessions` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`domain_id` integer,\n\t`mode` text DEFAULT 'socratic' NOT NULL,\n\t`state` text,\n\t`created_at` integer,\n\t`updated_at` integer,\n\tFOREIGN KEY (`domain_id`) REFERENCES `domains`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
  "CREATE TABLE `sf6_combos` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`character_slug` text NOT NULL,\n\t`notation` text NOT NULL,\n\t`situation` text,\n\t`status` text DEFAULT 'learning' NOT NULL,\n\t`damage` integer,\n\t`drive_cost` integer,\n\t`notes` text,\n\t`created_at` integer NOT NULL\n);\n",
  "CREATE TABLE `sf6_tips` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`character_slug` text NOT NULL,\n\t`type` text NOT NULL,\n\t`title` text NOT NULL,\n\t`content` text NOT NULL,\n\t`notation` text,\n\t`source_title` text,\n\t`source_url` text,\n\t`created_at` integer NOT NULL\n);\n"
];
