import type React from "react";

export const S: Record<string, React.CSSProperties> = {
  main: { width: "100%", margin: "0 auto", flex: 1, minHeight: 0, display: "flex", flexDirection: "column", padding: "0 16px" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, padding: "14px 0", borderBottom: "1px solid var(--border)", flexWrap: "wrap" },
  select: { background: "var(--panel-2)", color: "var(--text)", border: "1px solid var(--border)", borderRadius: 8, padding: "7px 10px" },
  tabs: { display: "flex", background: "var(--panel-2)", border: "1px solid var(--border)", borderRadius: 8, overflow: "hidden" },
  tab: { background: "transparent", color: "var(--muted)", border: "none", padding: "7px 14px" },
  tabActive: { background: "var(--accent-2)", color: "#fff" },
  player: { marginTop: 12, background: "var(--panel)", border: "1px solid var(--border)", borderRadius: 12, padding: 10 },
  playerHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  x: { background: "transparent", border: "none", color: "var(--muted)", fontSize: 14 },
  thread: { flex: 1, overflowY: "auto", padding: "16px 0", display: "flex", flexDirection: "column", gap: 12 },
  empty: { color: "var(--muted)", textAlign: "center", margin: "auto", maxWidth: 460, lineHeight: 1.6 },
  row: { display: "flex" },
  bubble: { maxWidth: "82%", padding: "10px 13px", borderRadius: 14, lineHeight: 1.5, border: "1px solid var(--border)" },
  user: { background: "var(--user)", borderBottomRightRadius: 4 },
  assistant: { background: "var(--panel)", borderBottomLeftRadius: 4 },
  badge: { display: "inline-block", fontSize: 11, textTransform: "uppercase", letterSpacing: 0.5, color: "var(--accent)", marginBottom: 6 },
  opts: { display: "flex", flexDirection: "column", gap: 6, marginTop: 10 },
  opt: { textAlign: "left", background: "var(--panel-2)", color: "var(--text)", border: "1px solid var(--border)", borderRadius: 8, padding: "9px 12px", lineHeight: 1.4 },
  cites: { display: "flex", flexDirection: "column", gap: 6, marginTop: 10, paddingTop: 10, borderTop: "1px dashed var(--border)" },
  cite: { display: "flex", alignItems: "center", gap: 8, background: "var(--panel-2)", border: "1px solid var(--border)", borderRadius: 8, padding: "6px 9px", textAlign: "left", color: "var(--text)", fontSize: 12.5, width: "fit-content", maxWidth: "100%" },
  citeN: { color: "var(--accent)", fontWeight: 700 },
  citeLabel: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: 420 },
  citePlay: { color: "#6ee7a8", whiteSpace: "nowrap" },
  inputBar: { display: "flex", gap: 8, padding: "12px 0 18px", borderTop: "1px solid var(--border)" },
  textarea: { width: "100%", resize: "none", background: "var(--panel-2)", color: "var(--text)", border: "1px solid var(--border)", borderRadius: 10, padding: "11px 13px", lineHeight: 1.4, maxHeight: 160 },
  send: { background: "var(--accent-2)", color: "#fff", border: "none", borderRadius: 10, padding: "0 18px", fontWeight: 600, minWidth: 84 },
  review: { flex: 1, overflowY: "auto", padding: "16px 0", display: "flex", flexDirection: "column", gap: 16 },
  reviewBar: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap", color: "var(--text)" },
  card: { background: "var(--panel)", border: "1px solid var(--border)", borderRadius: 14, padding: 18 },
  slideImg: { flex: "1 1 240px", minWidth: 220, aspectRatio: "4 / 3", background: "#1e222b", border: "1px solid var(--border)", borderRadius: 10, overflow: "hidden" },
};
